name: Test Access to VCC Repositories

on:
  workflow_dispatch:

jobs:
  access-to-github-action:
    runs-on: ubuntu-latest
    env:
      USER_AGENT: vrc-get/1.8.1 (+https://github.com/vrc-get/vrc-get)
    steps:
      - name: Try to acccess VRChat Official Repository
        if: always()
        run: |
          curl -vL -H "User-Agent: $USER_AGENT" 'https://packages.vrchat.com/official?download'
      - name: Try to acccess VRChat Curated Repository
        if: always()
        run: |
          curl -vL -H "User-Agent: $USER_AGENT" 'https://packages.vrchat.com/curated?download'
